Add spilling and transfer support for storage service
mars-project/mars pull request #2100
Opened 2021-04-20 13:57 UTC by hekaisheng

## What do these changes do?

- [ ] transfer
- [ ] spilling 
- [ ] spill strategy
- [ ] transfer for cuda

2021-05-12 09:25 UTC, chaokunyang commented on mars/deploy/oscar/pool.py
> +        address, n_process=n_process + 1,
Why changed to `n_process + 1`?

2021-05-17 11:28 UTC, qinxuye reviewed
LGTM overall, some comments are left.

2021-05-17 11:28 UTC, qinxuye commented on mars/services/storage/core.py
>      async def prefetch(self,
We could rename prefetch with fetch.

2021-05-17 11:28 UTC, qinxuye commented on mars/services/storage/transfer.py
> +class SendMessage:
Could rename `SendMessage` to `TransferInfo`.

2021-05-17 11:28 UTC, qinxuye commented on mars/services/storage/transfer.py
> +                message = SendMessage(part_data, session_id, data_key, level, is_eof)
Please check that data is not copied during serialization.

2021-05-17 11:28 UTC, qinxuye commented on mars/storage/base.py
> +    def spill_level(self):
If spill is not implemented in this PR, remove it first.

2021-05-17 11:28 UTC, qinxuye commented on mars/storage/plasma.py
> +        except plasma.PlasmaObjectNotFound:
This may happen for vineyard storage as well?

2021-05-17 11:28 UTC, qinxuye commented on mars/storage/shared_memory.py
> +        _shared_memory_manager.register(self._object_id, self.shm)
This mechanism may be different now.

2021-05-19 06:24 UTC, qinxuye reviewed
Some comments are left.

2021-05-19 06:24 UTC, qinxuye commented on mars/services/storage/core.py
> +    async def release_size(self,
Inconsistent API name, maybe rename to `release_quota`?

2021-05-19 06:24 UTC, qinxuye commented on mars/services/storage/transfer.py
> +            task.cancel()
Cancel stuff seems not covered, please make a double check.

2021-05-19 06:24 UTC, qinxuye commented on mars/storage/plasma.py
> +            pass
Not covered, check it please.

2021-05-21 09:06 UTC, qinxuye submitted a review, later dismissed
LGTM

2021-05-21 10:23 UTC, wjsi commented on mars/services/storage/transfer.py
> +        block_size = block_size or options.worker.transfer_block_size
Stop using options here. Use service start configuration first.

2021-05-21 10:39 UTC, wjsi commented on mars/services/storage/transfer.py
> +                is_eof = len(part_data) < block_size
It is better to judge EOF by comparing total transmitted size.

2021-05-21 14:53 UTC, wjsi commented on mars/services/storage/api/oscar.py
> +                    band: str = None,
Use `band_name` instead of `band` as `band` usually refer to address-name tuples?

2021-05-21 14:55 UTC, wjsi commented on mars/services/storage/core.py
> +        await self._lock.acquire()
Use async-with block instead of try-finally block?

2021-05-21 14:58 UTC, wjsi commented on mars/oscar/backends/mars/backend.py
> +        n_io_process = kwargs.pop('n_io_process', 0)
What will happen if we do not have a io process?

2021-05-21 15:14 UTC, wjsi requested changes

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/core.py
> +    async def allocate_size(self,
Rename to `request_quota`.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/core.py
> +                meta_api = await self._get_meta_api(session_id)
I think we need some comments here or change the exception raised, as other contributors may think we may implement `fetch` under this scenario someday.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/transfer.py
> +class TransferMessage:
We may only serialize data classes with pickle, which is of low efficiency with large blocks. Try using Serializables instead.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/transfer.py
> +            await self._storage_manager_ref.release_quota(
Do we need a unified cleanup method to handle both successes and errors, for instance writer cleanup? something is surely missing here.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/tests/test_transfer.py
> +async def test_cancel_transfer(create_actors):
Make sure everything is released in tests.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/tests/test_transfer.py
> +async def test_simple_transfer(create_actors):
Make sure everything is released in tests.

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/core.py
> +            await self._lock.acquire()
Ditto

2021-05-21 15:14 UTC, wjsi commented on mars/services/storage/core.py
> +        await self._lock.acquire()
Ditto

2021-05-25 08:07 UTC, wjsi approved these changes
LGTM

2021-05-25 08:26 UTC, qinxuye approved these changes
LGTM

2021-05-25 08:26 UTC, merged