Add storage infos in web
mars-project/mars pull request #2317
Opened 2021-08-10 04:11 UTC by hekaisheng

## What do these changes do?

Display storage infos in web

## Related issue number

Fixes #2158

2021-08-10 07:32 UTC, wjsi requested changes
`set_node_disk_info` not called. Pease also revert changes in `package-lock.json` and use `npm>=7.0.0`.

2021-08-10 07:32 UTC, wjsi commented on mars/services/storage/core.py
> +        self.ref().upload_storage_info.tell_delay(delay=1)
Set the return value to `self._upload_task`.

2021-08-10 07:32 UTC, wjsi commented on mars/services/storage/core.py
> +            self.ref().upload_storage_info.tell_delay(delay=1)
Ditto.

2021-08-10 07:32 UTC, wjsi commented on mars/services/storage/core.py
> +            await self._cluster_api.set_band_storage_info.batch(*upload_tasks)
Will this call block the actor?

2021-08-10 09:37 UTC, wjsi requested changes

2021-08-10 09:37 UTC, wjsi commented on mars/services/storage/core.py
> +            if 'disk' in self._init_params:
`and`

2021-08-10 09:37 UTC, wjsi commented on mars/services/storage/core.py
> +            await self._cluster_api.set_band_storage_info.batch(*upload_tasks)
Make upload task an independent while-true task started in `__post_create__`.

2021-08-11 03:09 UTC, wjsi approved these changes
LGTM

2021-08-11 03:14 UTC, qinxuye approved these changes
LGTM

2021-08-11 03:14 UTC, merged