Fix the error when multiple subtasks fetch the same data
mars-project/mars pull request #2322
Opened 2021-08-10 14:46 UTC by hekaisheng

## What do these changes do?

When multiple subtasks fetch the same key at the same time, the transfer task may fails. In this PR, `ReceiverManagerActor` holds a dict to record the data keys being fetched and create events to mark if transfer tasks are finished, `SenderManagerActor` will wait those events to make sure all data keys are sent.

## Related issue number

Fixes #2321

2021-08-12 07:11 UTC, wjsi requested changes

2021-08-12 07:11 UTC, wjsi commented on mars/services/storage/transfer.py
> +                        writer, data_size, level = self._key_to_writer_info[
When deciding to cancel certain transfer task, it shall be popped from `_key_to_writer_info` immediately, or there might be race conditions.

2021-08-12 07:11 UTC, wjsi commented on mars/services/storage/transfer.py
> +                        write_task.cancel()
Wait for cancelling?

2021-08-13 03:40 UTC, wjsi approved these changes
LGTM

2021-08-13 03:58 UTC, qinxuye approved these changes
LGTM

2021-08-13 03:58 UTC, merged